INSERT INTO country (code, name) VALUES
    ('AF', 'Afeganistão'),
    ('ZA', 'África do Sul'),
    ('AL', 'Albânia'),
    ('DE', 'Alemanha'),
    ('AD', 'Andorra'),
    ('AO', 'Angola'),
    ('AI', 'Anguilla'),
    ('AG', 'Antígua e Barbuda'),
    ('SA', 'Arábia Saudita'),
    ('DZ', 'Argélia'),
    ('AR', 'Argentina'),
    ('AM', 'Armênia'),
    ('AU', 'Austrália'),
    ('AT', 'Áustria'),
    ('AZ', 'Azerbaijão'),
    ('BS', 'Bahamas'),
    ('BD', 'Bangladesh'),
    ('BB', 'Barbados'),
    ('BH', 'Bahrein'),
    ('BY', 'Bielorrússia'),
    ('BE', 'Bélgica'),
    ('BZ', 'Belize'),
    ('BJ', 'Benim'),
    ('BT', 'Butão'),
    ('BO', 'Bolívia'),
    ('BA', 'Bósnia e Herzegovina'),
    ('BW', 'Botswana'),
    ('BR', 'Brasil'),
    ('BN', 'Brunei'),
    ('BG', 'Bulgária'),
    ('BF', 'Burkina Faso'),
    ('BI', 'Burundi'),
    ('CV', 'Cabo Verde'),
    ('KH', 'Camboja'),
    ('CM', 'Camarões'),
    ('CA', 'Canadá'),
    ('QA', 'Catar'),
    ('KZ', 'Cazaquistão'),
    ('TD', 'Chade'),
    ('CL', 'Chile'),
    ('CN', 'China'),
    ('CY', 'Chipre'),
    ('VA', 'Cidade do Vaticano'),
    ('CO', 'Colômbia'),
    ('KM', 'Comores'),
    ('CG', 'Congo'),
    ('KP', 'Coreia do Norte'),
    ('KR', 'Coreia do Sul'),
    ('CI', 'Costa do Marfim'),
    ('CR', 'Costa Rica'),
    ('HR', 'Croácia'),
    ('CU', 'Cuba'),
    ('DK', 'Dinamarca'),
    ('DJ', 'Djibuti'),
    ('DM', 'Dominica'),
    ('EG', 'Egito'),
    ('SV', 'El Salvador'),
    ('AE', 'Emirados Árabes Unidos'),
    ('EC', 'Equador'),
    ('ER', 'Eritreia'),
    ('SK', 'Eslováquia'),
    ('SI', 'Eslovênia'),
    ('ES', 'Espanha'),
    ('US', 'Estados Unidos'),
    ('EE', 'Estônia'),
    ('ET', 'Etiópia'),
    ('FJ', 'Fiji'),
    ('PH', 'Filipinas'),
    ('FI', 'Finlândia'),
    ('FR', 'França'),
    ('GA', 'Gabão'),
    ('GM', 'Gâmbia'),
    ('GH', 'Gana'),
    ('GE', 'Geórgia'),
    ('GD', 'Granada'),
    ('GR', 'Grécia'),
    ('GT', 'Guatemala'),
    ('GY', 'Guiana'),
    ('GN', 'Guiné'),
    ('GW', 'Guiné-Bissau'),
    ('GQ', 'Guiné Equatorial'),
    ('HT', 'Haiti'),
    ('NL', 'Holanda'),
    ('HN', 'Honduras'),
    ('HU', 'Hungria'),
    ('YE', 'Iêmen'),
    ('MH', 'Ilhas Marshall'),
    ('SB', 'Ilhas Salomão'),
    ('IN', 'Índia'),
    ('ID', 'Indonésia'),
    ('IR', 'Irã'),
    ('IQ', 'Iraque'),
    ('IE', 'Irlanda'),
    ('IS', 'Islândia'),
    ('IL', 'Israel'),
    ('IT', 'Itália'),
    ('JM', 'Jamaica'),
    ('JP', 'Japão'),
    ('JO', 'Jordânia'),
    ('KW', 'Kuwait'),
    ('LA', 'Laos'),
    ('LS', 'Lesoto'),
    ('LV', 'Letônia'),
    ('LB', 'Líbano'),
    ('LR', 'Libéria'),
    ('LY', 'Líbia'),
    ('LI', 'Liechtenstein'),
    ('LT', 'Lituânia'),
    ('LU', 'Luxemburgo'),
    ('MG', 'Madagascar'),
    ('MV', 'Maldivas'),
    ('MY', 'Malásia'),
    ('MW', 'Malawi'),
    ('ML', 'Mali'),
    ('MT', 'Malta'),
    ('MA', 'Marrocos'),
    ('MU', 'Maurício'),
    ('MR', 'Mauritânia'),
    ('MX', 'México'),
    ('MM', 'Mianmar'),
    ('FM', 'Micronésia'),
    ('MZ', 'Moçambique'),
    ('MD', 'Moldávia'),
    ('MC', 'Mônaco'),
    ('MN', 'Mongólia'),
    ('ME', 'Montenegro'),
    ('NA', 'Namíbia'),
    ('NR', 'Nauru'),
    ('NP', 'Nepal'),
    ('NI', 'Nicarágua'),
    ('NE', 'Níger'),
    ('NG', 'Nigéria'),
    ('NO', 'Noruega'),
    ('NZ', 'Nova Zelândia'),
    ('OM', 'Omã'),
    ('PW', 'Palau'),
    ('PA', 'Panamá'),
    ('PG', 'Papua-Nova Guiné'),
    ('PK', 'Paquistão'),
    ('PY', 'Paraguai'),
    ('PE', 'Peru'),
    ('PL', 'Polônia'),
    ('PT', 'Portugal'),
    ('KE', 'Quênia'),
    ('KG', 'Quirguistão'),
    ('UK', 'Reino Unido'),
    ('CF', 'República Centro-Africana'),
    ('CZ', 'República Tcheca'),
    ('DO', 'República Dominicana'),
    ('RO', 'Romênia'),
    ('RW', 'Ruanda'),
    ('RU', 'Rússia'),
    ('WS', 'Samoa'),
    ('LC', 'Santa Lúcia'),
    ('SM', 'San Marino'),
    ('ST', 'São Tomé e Príncipe'),
    ('SN', 'Senegal'),
    ('SL', 'Serra Leoa'),
    ('RS', 'Sérvia'),
    ('SG', 'Singapura'),
    ('SY', 'Síria'),
    ('SO', 'Somália'),
    ('LK', 'Sri Lanka'),
    ('SZ', 'Suazilândia'),
    ('SD', 'Sudão'),
    ('SS', 'Sudão do Sul'),
    ('SE', 'Suécia'),
    ('CH', 'Suíça'),
    ('SR', 'Suriname'),
    ('TH', 'Tailândia'),
    ('TW', 'Taiwan'),
    ('TZ', 'Tanzânia'),
    ('TJ', 'Tajiquistão'),
    ('TL', 'Timor-Leste'),
    ('TG', 'Togo'),
    ('TO', 'Tonga'),
    ('TT', 'Trinidad e Tobago'),
    ('TN', 'Tunísia'),
    ('TM', 'Turcomenistão'),
    ('TR', 'Turquia'),
    ('TV', 'Tuvalu'),
    ('UA', 'Ucrânia'),
    ('UG', 'Uganda'),
    ('UY', 'Uruguai'),
    ('UZ', 'Uzbequistão'),
    ('VU', 'Vanuatu'),
    ('VE', 'Venezuela'),
    ('VN', 'Vietnã'),
    ('ZM', 'Zâmbia'),
    ('ZW', 'Zimbábue')
ON CONFLICT (code) DO NOTHING;;