spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME:my_app_prod}
    username: ${DB_USER:prod_user}
    password: ${DB_PASSWORD:prod_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  flyway:
    url: jdbc:postgresql://localhost:5432/${DB_NAME:my_app_prod}
    user: ${DB_USER:prod_user}
    password: ${DB_PASSWORD:prod_password}
