spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME:my_app_prod}
    username: ${DB_USER:prod_user}
    password: ${DB_PASSWORD:prod_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate.format_sql: false

  logging:
    level:
      org.hibernate.SQL: error
      org.hibernate.type.descriptor.sql.BasicBinder: error
